[tox]
envlist = py26, py27, py33, py34, py35, flake8, check

[testenv:flake8]
basepython=python
deps=flake8
commands=flake8 fluctmatch

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/fluctmatch
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pip install -U pip
    py.test --basetemp={envtmpdir}

[testenv:check]
commands = py.test --cov={envsitepackagesdir}/fluctmatch --cov-report=term
deps =
    -r{toxinidir}/requirements_dev.txt
    pytest
    coverage
    pytest-cov

[pytest]
python_files = test_*.py
norecursedirs = .tox

; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following lines:
; deps =
;     -r{toxinidir}/requirements.txt
