name: Pyright Type Checking

on:
  push:
    branches:
      - main
      - develop

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'poetry'

      - name: Add poetry bin directory to PATH  # Add poetry bin directory to PATH for pyright
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - uses: jakebailey/pyright-action@v2  # Run pyright action
